version: "3"

services:
  backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5000:8000"
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    # environment:
    # POSTGRES_USER: ${POSTGRES_USER}
    # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # POSTGRES_DB: ${POSTGRES_DB}
    # POSTGRES_HOST: db
    # POSTGRES_HOSTNAME: db
    #   DATABASE_PORT: ${DATABASE_PORT}
    #   REDIS_CACHE_PASSWORD: ${REDIS_CACHE_PASSWORD}
    #   REDIS_CACHE_PORT: ${REDIS_CACHE_PORT}
  #   #   REDIS_CACHE_HOST: ${REDIS_CACHE_HOST}
  

